version: '3.8'
 
services:
    db:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=somerootpass
            - MYSQL_PASSWORD=somepass
            - MYSQL_DATABASE=symfony_db
            - MYSQL_USER=someuser
    web:
        build: .
        image: "jaggu199/symfony:1.0"
        ports:
            - 80:80